services:

  redis:
    image: 'redis:8.8-m03-alpine'
    restart: always
    container_name: redis
    volumes:
      - './redis_cache:/data'
    expose:
      - '6379'

  qdrant:
    image: 'qdrant/qdrant:v1.17'
    restart: always
    container_name: qdrant
    volumes:
      - './qdrant_data:/qdrant/storage'
    ports:
      - '6333:6333'

  mariadb:
    image: 'mariadb:12.2.2-noble'
    restart: always
    container_name: mariadb
    volumes:
      - './mariadb:/var/lib/mysql'
    env_file:
      - global_config.env
    expose:
      - '3306'
    command: '--max_allowed_packet=268435456'

  phpmyadmin:
    image: 'phpmyadmin:5.2.3'
    restart: always
    container_name: phpmyadmin
    env_file:
      - global_config.env
    ports:
      - '16000:80'
    depends_on:
      redis:
        condition: service_started
      qdrant:
        condition: service_started
      mariadb:
        condition: service_started

  data_streamer:
    build:
      context: .
      dockerfile: ./data_streamer/Dockerfile
    restart: always
    container_name: data-streamer
    ports:
      - '16001:8000'
    env_file:
      - global_config.env
    volumes:
      - './logs:/app/logs'
    depends_on:
      redis:
        condition: service_started
      qdrant:
        condition: service_started
      mariadb:
        condition: service_started

  embeddings:
    build:
      context: .
      dockerfile: ./embeddings/Dockerfile
    restart: always
    container_name: dembeddings
    ports:
      - '16002:8001'
    env_file:
      - global_config.env
    volumes:
      - './logs:/app/logs'
    depends_on:
      redis:
        condition: service_started
      qdrant:
        condition: service_started
      mariadb:
        condition: service_started
